name: pinact

on:
  pull_request:
    paths:
      - ".github/**"

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  pinact:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false
      - name: Pin actions
        uses: suzuki-shunsuke/pinact-action@5c5491051b56f602db279fe380abaf4112727eb2 # v0.2.2
        with:
          skip_push: "true"
