name: pinact

on:
  pull_request:
    paths:
      - ".github/**"

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  pinact:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
        with:
          persist-credentials: false
      - name: Pin actions
        uses: suzuki-shunsuke/pinact-action@a6896d13d22e2bf108a78b0c52d3f867c1f41b34 # v0.2.1
        with:
          skip_push: "true"
