name: pinact

on:
  pull_request:
    paths:
      - ".github/**"

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  pinact:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false
      - name: Pin actions
        uses: suzuki-shunsuke/pinact-action@5c5491051b56f602db279fe380abaf4112727eb2 # v0.2.2
        with:
          skip_push: "true"
